### ISSUE TITLE
Exception when opening solution with xUnit test project on Windows

### ISSUE THREAD

**Issue by autonomy-rocks** [xunit/xamarinstudio.xunit#22]
I'm using the latest stable version of Xamarin Studio 6.0.

I'm using all the latest xUnit NuGet packages for my test project.

Upon opening the solution that includes the test project, I get a fatal error. I cloned the repository (6.0 branch) and ran the add-in project, which starts a new Xamarin Studio instance with the add-in installed. When I open the project I get the following exception in the debugger:

System.InvalidCastException: Unable to cast transparent proxy to type 'Xunit.DiaSessionWrapperHelper'.
  at Server stack trace:
  at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\common\RemoteAppDomainManager.cs:58
  at Xunit.DiaSessionWrapper..ctor(String assemblyFilename) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility.desktop\Utility\DiaSessionWrapper.cs:20
  at Xunit.VisualStudioSourceInformationProvider..ctor(String assemblyFileName) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility.desktop\Frameworks\VisualStudioSourceInformationProvider.cs:21
  at Xunit.XunitFrontController..ctor(String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:58
  at MonoDevelop.XUnit.XUnitTestRunner.BuildTestInfo(String assembly) in C:\Users\tonys\Documents\Projects\xamarinstudio.xunit-6.0\MonoDevelop.XUnit\XUnitTestRunner.cs:66
  at MonoDevelop.XUnit.XUnitTestRunner.GetTestInfo(String assembly, String[] supportAssemblies) in C:\Users\tonys\Documents\Projects\xamarinstudio.xunit-6.0\MonoDevelop.XUnit\XUnitTestRunner.cs:46
  at at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
  at at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
  at Exception rethrown at [0]:
  at at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
  at at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
  at at MonoDevelop.XUnit.XUnitTestRunner.GetTestInfo(String assembly, String[] supportAssemblies)
  at MonoDevelop.XUnit.XUnitTestLoader.RunAsyncLoadTestInfo(XUnitTestInfoCache cache) in C:\Users\tonys\Documents\Projects\xamarinstudio.xunit-6.0\MonoDevelop.XUnit\XUnitTestLoader.cs:118
  at MonoDevelop.XUnit.XUnitTestLoader.<>c__DisplayClass2_0.<AsyncLoadTestInfo>b__0() in C:\Users\tonys\Documents\Projects\xamarinstudio.xunit-6.0\MonoDevelop.XUnit\XUnitTestLoader.cs:59
  at at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
  at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at at System.Threading.ThreadHelper.ThreadStart()

**Comment by autonomy-rocks** [comment]
And if I switch xunit.runner.utility to version 2.1.0 and fix the compilation errors (change all instances of `using (var controller = new XunitFrontController(assembly, null, false))` to `using (var controller = new XunitFrontController(AppDomainSupport.IfAvailable, assembly, null, false))`) then I get the following stack trace with the same exception.

System.InvalidCastException: Unable to cast transparent proxy to type 'Xunit.DiaSessionWrapperHelper'.
  at Server stack trace:
  at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\BuildAgent\work\cb37e9acf085d108\src\common\AppDomainManager_AppDomain.cs:57
  at Xunit.DiaSessionWrapper..ctor(String assemblyFilename) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility.desktop\Utility\DiaSessionWrapper.cs:20
  at Xunit.VisualStudioSourceInformationProvider..ctor(String assemblyFileName) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility.desktop\Frameworks\VisualStudioSourceInformationProvider.cs:21
  at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:64
  at MonoDevelop.XUnit.XUnitTestRunner.BuildTestInfo(String assembly) in C:\Users\tonys\Documents\Projects\xamarinstudio.xunit-6.0\MonoDevelop.XUnit\XUnitTestRunner.cs:66
  at MonoDevelop.XUnit.XUnitTestRunner.GetTestInfo(String assembly, String[] supportAssemblies) in C:\Users\tonys\Documents\Projects\xamarinstudio.xunit-6.0\MonoDevelop.XUnit\XUnitTestRunner.cs:46
  at at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
  at at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
  at Exception rethrown at [0]:
  at at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
  at at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
  at at MonoDevelop.XUnit.XUnitTestRunner.GetTestInfo(String assembly, String[] supportAssemblies)
  at MonoDevelop.XUnit.XUnitTestLoader.RunAsyncLoadTestInfo(XUnitTestInfoCache cache) in C:\Users\tonys\Documents\Projects\xamarinstudio.xunit-6.0\MonoDevelop.XUnit\XUnitTestLoader.cs:118
  at MonoDevelop.XUnit.XUnitTestLoader.<>c__DisplayClass2_0.<AsyncLoadTestInfo>b__0() in C:\Users\tonys\Documents\Projects\xamarinstudio.xunit-6.0\MonoDevelop.XUnit\XUnitTestLoader.cs:59
  at at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
  at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at at System.Threading.ThreadHelper.ThreadStart()

**Comment by autonomy-rocks** [comment]
I've managed to solve this problem by making the following modifications in `XUnitTestLoader.RunAsyncLoadTestInfo`. However, the project still doesn't work as expected (tests completely fail to run, even though they're now detected). It seems this exception is caused somehow by being in an external process.

```
var runner = new XUnitTestRunner()
testInfo = runner.GetTestInfo(testSuite.AssemblyPath, testSuite.SupportAssemblies.ToArray());

//using (var runner = (XUnitTestRunner)Runtime.ProcessService.CreateExternalProcessObject(typeof(XUnitTestRunner), false)) {
//  testInfo = runner.GetTestInfo(testSuite.AssemblyPath, testSuite.SupportAssemblies.ToArray());
//}
```

**Comment by lextm** [comment]
Please provide a smallest reproducible sample project with steps to show me how to reproduce. 

Your changes so far do not yet hit the root cause, so I'd like to do more debugging. Thanks.

**Comment by autonomy-rocks** [comment]
I don't know how to explain it with any more detail than that. It's a problem with AppDomains.

From what I understand, the problem is that you've created a thread to load the tests, and then within that thread you also try to create an external process. And then within that external process, you try to create an instance of `XunitFrontController` which tries to do some reflection. I don't quite understand why it breaks when this happens. But I do understand that it's rather pointless to create a thread to load the tests, and then within that same thread create an external process that actually loads the tests. Only one or the other is necessary.

There are two calls to `XunitFrontController` within the code. The other one is also within a call to `CreateExternalProcessObject`. That one doesn't throw an exception. However, it fails to report the status of the tests unless I make the same modifications to that call that I had to make to the other call. I haven't figured out the cause for this.

I've been working on this for quite some hours now, and I've found quite a few issues. There's an option in the latest stable Xamarin Studio 6.0, Tools->Options, then Text Editor->Source Analysis. Check `Enable text editor unit test integration`. Currently the dots are shown next to unit tests. However, the status of the unit test isn't shown. Attempting to run, debug, etc from a single test also doesn't work.

Honestly, I'm in the process of writing a new version from scratch because I think that's what this needs. I think too many changes have happened within MonoDevelop between 5.0 and 6.0, and it warrants a complete rewrite of the add-in. I plan on switching MonoDevelop full time because Visual Studio has become slow lately, and this started as me trying to get xUnit working so that I could write an add-in for continuous testing, as well as some other ReSharper-like add-ins.

**Comment by lextm** [comment]
Whether the issues you met is related to app domains is unclear. You modified the code without fully understanding it, and that's why I asked for a sample project to debug on my own.

It is interesting that everybody would like to have a "complete rewrite", instead of really understand the code first and move it in the right direction. You can take your time if you intend to, as that's your time.

I do expect new issues when I took over the ownership of this repo, but if you check the progress, many long time issues have already been analyzed and closed in the past few weeks. 

New features in Xamarin Studio 6 require more investigation than ever (like the "text editor unit test integration"), and certainly they will be supported once we know for sure how the NUnit add-in supports them.

The two `XunitFrontController` instances are used for different purposes. The one in `XUnitTestRunner.BuildTestInfo` is used to query test cases and update the panel. The other in `XUnitTestRunner.Execute` is used to execute the actual test cases.

`CreateExternalProcessObject` is very important here, as it allows instances of `XUnitTestRunner` to be hosted in separate processes. That protects Xamarin Studio process from being harmed by unit test cases. A new thread is used within the add-in, so that this piece of code won't freeze the unit test panel (as far as I can tell).

Replacing the external `XUnitTestRunner` with a local instance is not the solution. I'd rather do more debugging to see what is the actual error.

Meanwhile, this add-in currently uses `xunit.runner.utility` 2.1.0-beta1, so it should work fine with xUnit.net 2.1.0 based test projects. Are you using 2.2.0-beta1 in your project? That's something I never tested, and issues are expected.

**Comment by autonomy-rocks** [comment]
I'm using xUnit 2.1 in all of my projects. I've tried getting this project to work with the default 2.1.0-beta1 version, standard 2.1.0, and 2.2.0-beta, and all have similar issues.

I didn't think that running the tests in a local instance was a good solution. I was just testing that to see where the issue was. As far as using threads, from what I understand, the actual loading of the test data is done within the external process object that is created. So that would eliminate the need to use a thread, as the external process object shouldn't be causing the unit test panel to freeze. I think as far as that area of code goes, getting rid of the threading would probably solve that issue.

**Comment by autonomy-rocks** [comment]
As far as reproducing the issue, my operating system is Windows 10 32 bit and I'm using the latest XS 6.0 stable. All I did was add the add in from within Xamarin Studio and open a xUnit test project. Upon opening the project, for me it causes a fatal error. Sometimes I had to click the run menu or open the unit tests pad and click run all to get the fatal error. But essentially, as soon as it attempts to load the tests, it encounters the exception and causes XS to crash.

My test projects are all xUnit 2.1 stable.

**Comment by lextm** [comment]
The fatal exception was caused by .NET Remoting related exceptions. It seems that the mdhost.exe failed to load the necessary assemblies into itself.

This only happens on Windows, so I guess it's either caused by Xamarin Studio's Windows build, or .NET Framework.

Will soon publish a new build to address the crash, but I did not yet let the test cases run.

**Comment by lextm** [comment]
If you do want to debug mdhost.exe, the tip is as below,
1. Insert `Thread.Sleep(20000)` in `XUnitTestRunner.Execute` so that mdhost.exe hangs for the debugger to attach.
2. Use WinDbg to attach to that process and debug the managed exception.

**Comment by lextm** [comment]
Fixed in 2e148f903cb04605055305ef575fa5c29fe9ca00

**Comment by lextm** [comment]
Open #25 to track the remaining task.

**Comment by autonomy-rocks** [comment]
Switching to NullSourceInformationProvider didn't actually solve the problem. An Exception is still thrown. The new Exception is now:

```
System.InvalidCastException: Unable to cast transparent proxy to type 'Xunit.Abstractions.IAssemblyInfo'.
  at Server stack trace:
  at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\common\RemoteAppDomainManager.cs:58
  at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:65
  at Xunit.XunitFrontController.CreateInnerController() in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:107
  at Xunit.XunitFrontController.get_InnerController() in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:73
  at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:136
  at MonoDevelop.XUnit.XUnitTestRunner.BuildTestInfo(String assembly) in C:\Users\tonys\Documents\Projects\tstivers1990\xamarinstudio.xunit.git\MonoDevelop.XUnit\XUnitTestRunner.cs:68
  at MonoDevelop.XUnit.XUnitTestRunner.GetTestInfo(String assembly, String[] supportAssemblies) in C:\Users\tonys\Documents\Projects\tstivers1990\xamarinstudio.xunit.git\MonoDevelop.XUnit\XUnitTestRunner.cs:46
  at at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
  at at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
  at Exception rethrown at [0]:
  at at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
  at at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
  at at MonoDevelop.XUnit.XUnitTestRunner.GetTestInfo(String assembly, String[] supportAssemblies)
  at MonoDevelop.XUnit.XUnitTestLoader.RunAsyncLoadTestInfo(XUnitTestInfoCache cache) in C:\Users\tonys\Documents\Projects\tstivers1990\xamarinstudio.xunit.git\MonoDevelop.XUnit\XUnitTestLoader.cs:118
  at MonoDevelop.XUnit.XUnitTestLoader.<>c__DisplayClass2_0.<AsyncLoadTestInfo>b__0() in C:\Users\tonys\Documents\Projects\tstivers1990\xamarinstudio.xunit.git\MonoDevelop.XUnit\XUnitTestLoader.cs:59
  at at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
  at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by lextm** [comment]
I think after some further debugging I am able to tell the root cause. So re-opening this issue.

WinDbg gives the following AppDomain report,

```
0:005> !dumpdomain
--------------------------------------
System Domain:      745469c0
LowFrequencyHeap:   74546ce4
HighFrequencyHeap:  74546d30
StubHeap:           74546d7c
Stage:              OPEN
Name:               None
--------------------------------------
Shared Domain:      74546670
LowFrequencyHeap:   74546ce4
HighFrequencyHeap:  74546d30
StubHeap:           74546d7c
Stage:              OPEN
Name:               None
Assembly:           00ed3188 [C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll]
ClassLoader:        00ecd860
  Module Name
729b1000    C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll

--------------------------------------
Domain 1:           00eaf1a0
LowFrequencyHeap:   00eaf60c
HighFrequencyHeap:  00eaf658
StubHeap:           00eaf6a4
Stage:              OPEN
SecurityDescriptor: 00eb0238
Name:               mdhost.exe
Assembly:           00ed3188 [C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll]
ClassLoader:        00ecd860
SecurityDescriptor: 00ecfe10
  Module Name
729b1000    C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll

Assembly:           00ed3970 [C:\Program Files (x86)\Xamarin Studio\bin\mdhost.exe]
ClassLoader:        00edebf0
SecurityDescriptor: 00edeb08
  Module Name
00d63fbc    C:\Program Files (x86)\Xamarin Studio\bin\mdhost.exe

Assembly:           00ed3800 [C:\Program Files (x86)\Xamarin Studio\bin\MonoDevelop.Core.dll]
ClassLoader:        00eda898
SecurityDescriptor: 00edfd18
  Module Name
00d64e30    C:\Program Files (x86)\Xamarin Studio\bin\MonoDevelop.Core.dll

Assembly:           00ed38b8 [C:\Program Files (x86)\Xamarin Studio\bin\Mono.Addins.dll]
ClassLoader:        00ef8510
SecurityDescriptor: 00ee02f0
  Module Name
00d6a848    C:\Program Files (x86)\Xamarin Studio\bin\Mono.Addins.dll

Assembly:           00ed3240 [C:\Program Files (x86)\Xamarin Studio\bin\Mono.Addins.Setup.dll]
ClassLoader:        00ee9c68
SecurityDescriptor: 00edfda0
  Module Name
00d6b388    C:\Program Files (x86)\Xamarin Studio\bin\Mono.Addins.Setup.dll

Assembly:           00ed3690 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll]
ClassLoader:        00ef3cd8
SecurityDescriptor: 00ee0598
  Module Name
71e91000    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

Assembly:           00ed3748 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll]
ClassLoader:        00f15ed0
SecurityDescriptor: 00ee0510
  Module Name
627a1000    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll

Assembly:           00ed3ae0 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll]
ClassLoader:        00f15920
SecurityDescriptor: 00ee0268
  Module Name
6d1d1000    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

Assembly:           00ed3a28 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll]
ClassLoader:        00f16418
SecurityDescriptor: 00ee0950
  Module Name
6b811000    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

Assembly:           00ed3b98 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll]
ClassLoader:        00f16348
SecurityDescriptor: 00ee07b8
  Module Name
6b101000    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

Assembly:           00ed3c50 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll]
ClassLoader:        00f161a8
SecurityDescriptor: 00ee0400
  Module Name
6d2c1000    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll

Assembly:           00ed32f8 [C:\Users\lextm\Downloads\xamarinstudio.xunit\MonoDevelop.XUnit\bin\Debug\MonoDevelop.XUnit.dll]
ClassLoader:        00f158b8
SecurityDescriptor: 00edfc90
  Module Name
00fd2a38    C:\Users\lextm\Downloads\xamarinstudio.xunit\MonoDevelop.XUnit\bin\Debug\MonoDevelop.XUnit.dll

Assembly:           00ed3468 [C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll]
ClassLoader:        00f15988
SecurityDescriptor: 00f384b8
  Module Name
5da51000    C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll

Assembly:           00ed2ea8 [C:\Users\lextm\Downloads\xamarinstudio.xunit\MonoDevelop.XUnit\bin\Debug\xunit.abstractions.dll]
ClassLoader:        00f16070
SecurityDescriptor: 00f37d48
  Module Name
00fd4334    C:\Users\lextm\Downloads\xamarinstudio.xunit\MonoDevelop.XUnit\bin\Debug\xunit.abstractions.dll

Assembly:           00ed2df0 [C:\Users\lextm\Downloads\xamarinstudio.xunit\MonoDevelop.XUnit\bin\Debug\xunit.runner.utility.desktop.dll]
ClassLoader:        00f164e8
SecurityDescriptor: 00f38540
  Module Name
00fd4e4c    C:\Users\lextm\Downloads\xamarinstudio.xunit\MonoDevelop.XUnit\bin\Debug\xunit.runner.utility.desktop.dll

Assembly:           00ed3018 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll]
ClassLoader:        00f15fa0
SecurityDescriptor: 00f377f8
  Module Name
6cef1000    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll

Assembly:           00ed30d0 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll]
ClassLoader:        00f16008
SecurityDescriptor: 00f37908
  Module Name
68eb1000    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll

--------------------------------------
Domain 2:           00f4f128
LowFrequencyHeap:   00f4f594
HighFrequencyHeap:  00f4f5e0
StubHeap:           00f4f62c
Stage:              OPEN
SecurityDescriptor: 00f54108
Name:               xunit
Assembly:           00ed3188 [C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll]
ClassLoader:        00ecd860
SecurityDescriptor: 00f383a8
  Module Name
729b1000    C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll

Assembly:           00f5a2f8 [C:\Users\lextm\Documents\Projects\xunit\xunit\bin\Debug\xunit.execution.desktop.dll]
ClassLoader:        00f15b90
SecurityDescriptor: 00f37a18
  Module Name
01024928    C:\Users\lextm\Documents\Projects\xunit\xunit\bin\Debug\xunit.execution.desktop.dll

Assembly:           00f591b8 [C:\Users\lextm\Documents\Projects\xunit\xunit\bin\Debug\xunit.abstractions.dll]
ClassLoader:        00f15bf8
SecurityDescriptor: 00f37aa0
  Module Name
01025650    C:\Users\lextm\Documents\Projects\xunit\xunit\bin\Debug\xunit.abstractions.dll

Assembly:           00f59048 [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll]
ClassLoader:        00f162e0
SecurityDescriptor: 00f37b28
  Module Name
01025da8    C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

Assembly:           00f5a3b0 [C:\Users\lextm\Documents\Projects\xunit\xunit\bin\Debug\xunit.dll]
ClassLoader:        00f15c60
SecurityDescriptor: 00f37ff0
  Module Name
04e16a20    C:\Users\lextm\Documents\Projects\xunit\xunit\bin\Debug\xunit.dll
```

According to [this blog post](https://blogs.msdn.microsoft.com/suzcook/2003/07/21/assembly-identity/), the two copies of `xunit.abstractions.dll` loaded are considered "different from each other". Thus, casting types can easily lead to exceptions we observed.

Will further debug to see what's the best way to resolve it.

**Comment by lextm** [comment]
Disabling app domain seems to resolve this on Windows to make unit test case discovery work. Fixed in c605f046941cfc869620c66f96cb7149d626a29e

However test cases cannot run yet. There is another exception to address which will continue under #25
